version: '3.8'

services:
  app:
    build: .
    container_name: moneywars_app
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=db
      - DB_DATABASE=moneywars
      - DB_USERNAME=moneyuser
      - DB_PASSWORD=moneypass
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: moneywars_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moneywars
      MYSQL_USER: moneyuser
      MYSQL_PASSWORD: moneypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: moneywars_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
