
CREATE TABLE spendings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tgtdate DATE NOT NULL,
    tgtmoney INT NOT NULL,
    tgtitem INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE items (
    code INT PRIMARY KEY,
    name TEXT NOT NULL
);
